// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsyvmyvmiralheyieplo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzeXZteXZtaXJhbGhleWllcGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MjA5NzgsImV4cCI6MjA1MjE5Njk3OH0.6xS5Lr4exE3rZlEBf3bYYeGgxxpdqNk3tseEBCZU3s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);